import type { ReactElement } from 'react'
import Layout from '@/components/layout'
import type { NextPageWithLayout } from '@/pages/_app'
import Head from 'next/head'

const MyList: NextPageWithLayout = () => {
    return (
        <>
            <Head>
                <title>Superlista.ar | Productos</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Mi Lista</h1>
        </>
    )
}

MyList.getLayout = function getLayout(page: ReactElement) {
    return (
        <Layout>
            {page}
        </Layout>
    )
}

export default MyList
