import { NextPage } from 'next'
import Head from 'next/head'

import { IProduct } from '~/lib/types'
import { useProducts, useUtils } from '~/lib/hooks'

import ProductCard from '~/ui/components/ProductCard'

import styled from 'styled-components'
import { Title } from '~/ui/styles/sharedStyles'
import CategoriesCollapse from '~/ui/components/CategoriesCollapse'
import { useRouter } from 'next/router'

const Products: NextPage = () => {
  let products = useProducts()
  const { searchValue } = useUtils()

  const router = useRouter()
  const categoryQuery = router.query.slug

  products = !searchValue
    ? products
    : products.filter(product =>
      product.name.toLowerCase().includes(searchValue.toLocaleLowerCase())
    )

  if (categoryQuery) {
    products = products.filter((product) => {
      return product.categoryID === categoryQuery[0]
    })
  }

  return (
    <>
      <Head>
        <title>Superlista.ar | Productos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CategoriesCollapse />

      <Title>Productos</Title>

      <ProductsContainer>
        {
          products
            .map((product: IProduct) => {
              return (
                <ProductCard
                  id={product.id}
                  name={product.name}
                  img={product.img}
                  nota={product.nota}
                  categoryID={product.categoryID}
                  key={product.name}
                  product={product}
                />
              )
            })
        }
      </ProductsContainer>
    </>
  )
}

export default Products

const ProductsContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  grid-template-rows: 1fr;
  grid-column-gap: 3%;
  grid-row-gap: 8px;
  padding: 0 3%;
  width: 100%;
  transition: all .5s;
`
