import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Superlista.ar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Superlista.ar</h1>
      <Link href="/products">
        Empezar nueva lista
      </Link>
    </>
  )
}

export default Home
